- name: Collect remote logs
  hosts: all
  tasks:
  - name: Collect logs from containers
    shell: |
      /tmp/log-collector.sh {{ inventory_hostname }} {{ node_name }}
  - name: Collect perf results
    shell: |
      /tmp/perf.sh {{ inventory_hostname }} {{ node_name }}
  - name: Retrieve logs
    fetch:
      src: "/tmp/{{ inventory_hostname }}.tgz"
      dest: "{{ results_dir }}/"
      flat: yes
  - name: Retrieve perf logs
    fetch:
      src: "/tmp/{{ inventory_hostname }}-perf.tgz"
      dest: "{{ results_dir }}/"
      flat: yes
