- name: Configure docker
  hosts: all
  become: true
  tasks:

  - name: backup registries.conf
    copy:
      src: /etc/containers/registries.conf
      dest: /etc/containers/registries.conf.bak
      remote_src: yes

  - name: Configure insecure podman registry
    copy:
      src: "{{ rundir }}/registries.conf"
      dest: /etc/containers/registries.conf
