- name: Install ovn-tester
  hosts: tester_hosts
  tasks:
    - name: Pull latest containers
      shell: |
              set -e
              docker pull {{ registry_node }}:5000/ovn/ovn-tester
              docker tag {{ registry_node }}:5000/ovn/ovn-tester ovn/ovn-tester
